/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgentInfo {
  'principal' : Principal,
  'name' : string,
  'approvalStatus' : string,
  'contactNumber' : string,
}
export interface AgentPanelData {
  'agents' : Array<AgentInfo>,
  'agentStats' : {
    'totalAgents' : bigint,
    'pendingAgents' : bigint,
    'approvedAgents' : bigint,
    'approvalRate' : number,
    'rejectedAgents' : bigint,
    'rejectionRate' : number,
  },
  'recentChanges' : Array<AgentInfo>,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AttendanceAgentRecord {
  'agentName' : string,
  'checkInTime' : Time,
  'checkOutTime' : [] | [Time],
  'agentMobile' : string,
}
export interface AttendanceRecord {
  'id' : bigint,
  'faceVerification' : FaceVerificationResult,
  'agentName' : string,
  'agentId' : Principal,
  'checkInTime' : Time,
  'checkOutTime' : [] | [Time],
  'agentMobile' : string,
  'isValid' : boolean,
  'location' : LocationData,
}
export interface CsvAttendanceRecord {
  'faceVerification' : string,
  'agentName' : string,
  'checkInTime' : bigint,
  'attendanceDate' : bigint,
  'checkOutTime' : bigint,
  'agentMobile' : string,
  'location' : string,
}
export interface CsvReport {
  'agentName' : string,
  'attendanceRecords' : Array<CsvAttendanceRecord>,
  'agentMobile' : string,
}
export interface Customer {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'email' : [] | [string],
  'address' : [] | [string],
  'notes' : [] | [string],
  'phone' : [] | [string],
  'serviceHistory' : Array<ServiceRecord>,
}
export interface CustomerProfile {
  'name' : string,
  'email' : [] | [string],
  'phoneNumber' : string,
}
export interface CustomerQuery {
  'id' : bigint,
  'customerName' : string,
  'status' : QueryStatus,
  'flatType' : string,
  'rentRange' : bigint,
  'assignedAgent' : [] | [Principal],
  'createdAt' : Time,
  'contactPhone' : string,
}
export interface CustomerQueryResponse {
  'id' : bigint,
  'queryType' : string,
  'name' : string,
  'submittedAt' : Time,
  'email' : [] | [string],
  'message' : string,
  'phoneNumber' : string,
}
export interface FaceVerificationResult {
  'confidenceScore' : bigint,
  'message' : string,
  'isSuccess' : boolean,
  'faceDataHash' : string,
}
export interface FollowUp {
  'id' : bigint,
  'completed' : boolean,
  'dueDate' : Time,
  'notes' : [] | [string],
  'customerId' : bigint,
}
export interface Lead {
  'id' : bigint,
  'status' : LeadStatus,
  'assignedAgent' : [] | [Principal],
  'name' : string,
  'createdAt' : Time,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type LeadStatus = { 'new' : null } |
  { 'lost' : null } |
  { 'contacted' : null } |
  { 'converted' : null } |
  { 'qualified' : null };
export interface LocationData {
  'latitude' : number,
  'locationTimestamp' : bigint,
  'longitude' : number,
  'accuracy' : [] | [number],
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface MessageTemplate {
  'id' : bigint,
  'content' : string,
  'createdAt' : Time,
  'category' : TemplateCategory,
}
export interface OverviewMetrics {
  'recentCustomers' : Array<Customer>,
  'customerQueryStats' : {
    'openQueries' : bigint,
    'totalQueries' : bigint,
    'inProgressQueries' : bigint,
    'closedQueries' : bigint,
    'resolvedQueries' : bigint,
  },
  'rentQueries' : {
    'resolved' : bigint,
    'closed' : bigint,
    'total' : bigint,
    'open' : bigint,
    'inProgress' : bigint,
  },
  'validCheckIns' : bigint,
  'totalLeads' : bigint,
  'todayCheckIns' : bigint,
  'conversionRate' : number,
  'recentLeads' : Array<Lead>,
  'salesQueries' : {
    'resolved' : bigint,
    'closed' : bigint,
    'total' : bigint,
    'open' : bigint,
    'inProgress' : bigint,
  },
  'totalCustomers' : bigint,
  'interiorQueries' : {
    'resolved' : bigint,
    'closed' : bigint,
    'total' : bigint,
    'open' : bigint,
    'inProgress' : bigint,
  },
  'currentDayCheckIns' : bigint,
  'agentApprovalMetrics' : {
    'agentCountPerStatus' : {
      'pending' : bigint,
      'approved' : bigint,
      'rejected' : bigint,
    },
    'totalAgents' : bigint,
    'pendingAgents' : bigint,
    'approvedAgents' : bigint,
    'rejectedAgents' : bigint,
    'recentAgentApprovals' : Array<AgentInfo>,
  },
  'pendingFollowUps' : bigint,
  'recentFollowUps' : Array<FollowUp>,
}
export interface PaginatedAttendanceRecords {
  'total' : bigint,
  'records' : Array<AttendanceRecord>,
  'hasNextPage' : boolean,
}
export interface PaginatedCustomers {
  'total' : bigint,
  'hasNextPage' : boolean,
  'customers' : Array<Customer>,
}
export interface PaginatedLeads {
  'total' : bigint,
  'leads' : Array<Lead>,
  'hasNextPage' : boolean,
}
export type QueryStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export interface ServiceRecord {
  'cost' : [] | [bigint],
  'date' : Time,
  'description' : string,
}
export type TemplateCategory = { 'support' : null } |
  { 'sales' : null } |
  { 'followUp' : null } |
  { 'general' : null };
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : [] | [string],
  'contactNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WhatsAppConfig {
  'isActive' : boolean,
  'apiKey' : string,
  'businessNumber' : string,
}
export interface WhatsAppMessageLog {
  'id' : bigint,
  'messageContent' : string,
  'sentStatus' : boolean,
  'leadId' : [] | [bigint],
  'timestamp' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[Customer], bigint>,
  'addCustomerQuery' : ActorMethod<[CustomerQuery], bigint>,
  'addFollowUp' : ActorMethod<[FollowUp], bigint>,
  'addLead' : ActorMethod<[Lead], bigint>,
  'addTemplate' : ActorMethod<[MessageTemplate], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignLead' : ActorMethod<[bigint, Principal], undefined>,
  'changeAgentApprovalStatus' : ActorMethod<
    [Principal, ApprovalStatus],
    undefined
  >,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'deleteTemplate' : ActorMethod<[bigint], undefined>,
  'getAgentCustomerQueries' : ActorMethod<[Principal], Array<CustomerQuery>>,
  'getAgentPanelData' : ActorMethod<[], AgentPanelData>,
  'getAllAttendanceAgentRecords' : ActorMethod<
    [],
    Array<AttendanceAgentRecord>
  >,
  'getAllAttendanceRecords' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedAttendanceRecords
  >,
  'getAllCustomerQueries' : ActorMethod<[], Array<CustomerQuery>>,
  'getAllCustomers' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    PaginatedCustomers
  >,
  'getAllFollowUps' : ActorMethod<[], Array<FollowUp>>,
  'getAllLeads' : ActorMethod<[[] | [bigint], [] | [bigint]], PaginatedLeads>,
  'getAllTemplates' : ActorMethod<[], Array<MessageTemplate>>,
  'getAttendanceAgentRecords' : ActorMethod<
    [Principal],
    Array<AttendanceAgentRecord>
  >,
  'getAttendanceRecords' : ActorMethod<[Principal], Array<AttendanceRecord>>,
  'getAttendanceRecordsCsvReport' : ActorMethod<[Principal], CsvReport>,
  'getCRMDashboardData' : ActorMethod<
    [],
    {
      'templates' : Array<MessageTemplate>,
      'customerProfiles' : Array<CustomerProfile>,
      'messages' : Array<Message>,
      'leads' : Array<Lead>,
      'customerQueryResponses' : Array<CustomerQueryResponse>,
      'customerQueries' : Array<CustomerQuery>,
      'followUps' : Array<FollowUp>,
      'customers' : Array<Customer>,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getCustomerDashboardData' : ActorMethod<
    [string],
    {
      'queries' : Array<CustomerQueryResponse>,
      'confirmationMessage' : string,
      'profiles' : Array<CustomerProfile>,
    }
  >,
  'getCustomerPanels' : ActorMethod<
    [],
    {
      'rentPanel' : Array<CustomerQuery>,
      'salesPanel' : Array<CustomerQuery>,
      'interiorPanel' : Array<CustomerQuery>,
    }
  >,
  'getCustomerProfile' : ActorMethod<[bigint], [] | [CustomerProfile]>,
  'getCustomerProfileByPhone' : ActorMethod<[string], [] | [CustomerProfile]>,
  'getCustomerQueriesByPhoneNumber' : ActorMethod<
    [string],
    Array<CustomerQueryResponse>
  >,
  'getCustomerQuery' : ActorMethod<[bigint], [] | [CustomerQuery]>,
  'getFollowUp' : ActorMethod<[bigint], [] | [FollowUp]>,
  'getLead' : ActorMethod<[bigint], [] | [Lead]>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getOverviewMetrics' : ActorMethod<[], OverviewMetrics>,
  'getQueryConfirmationMessage' : ActorMethod<[], string>,
  'getTemplate' : ActorMethod<[bigint], [] | [MessageTemplate]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWhatsAppConfig' : ActorMethod<[], [] | [WhatsAppConfig]>,
  'getWhatsAppMessageLogs' : ActorMethod<[], Array<WhatsAppMessageLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'logWhatsAppMessage' : ActorMethod<[WhatsAppMessageLog], bigint>,
  'recordAttendance' : ActorMethod<[AttendanceRecord], bigint>,
  'registerCustomerProfile' : ActorMethod<[CustomerProfile], bigint>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], bigint>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setWhatsAppConfig' : ActorMethod<[WhatsAppConfig], undefined>,
  'submitCustomerQueryResponse' : ActorMethod<[CustomerQueryResponse], bigint>,
  'updateCustomer' : ActorMethod<[bigint, Customer], undefined>,
  'updateCustomerQuery' : ActorMethod<[bigint, CustomerQuery], undefined>,
  'updateFollowUp' : ActorMethod<[bigint, FollowUp], undefined>,
  'updateLead' : ActorMethod<[bigint, Lead], undefined>,
  'updateTemplate' : ActorMethod<[bigint, MessageTemplate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];