/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ServiceRecord = IDL.Record({
  'cost' : IDL.Opt(IDL.Nat),
  'date' : Time,
  'description' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'serviceHistory' : IDL.Vec(ServiceRecord),
});
export const QueryStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const CustomerQuery = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : QueryStatus,
  'flatType' : IDL.Text,
  'rentRange' : IDL.Nat,
  'assignedAgent' : IDL.Opt(IDL.Principal),
  'createdAt' : Time,
  'contactPhone' : IDL.Text,
});
export const FollowUp = IDL.Record({
  'id' : IDL.Nat,
  'completed' : IDL.Bool,
  'dueDate' : Time,
  'notes' : IDL.Opt(IDL.Text),
  'customerId' : IDL.Nat,
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'lost' : IDL.Null,
  'contacted' : IDL.Null,
  'converted' : IDL.Null,
  'qualified' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeadStatus,
  'assignedAgent' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const TemplateCategory = IDL.Variant({
  'support' : IDL.Null,
  'sales' : IDL.Null,
  'followUp' : IDL.Null,
  'general' : IDL.Null,
});
export const MessageTemplate = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Time,
  'category' : TemplateCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AgentInfo = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'approvalStatus' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const AgentPanelData = IDL.Record({
  'agents' : IDL.Vec(AgentInfo),
  'agentStats' : IDL.Record({
    'totalAgents' : IDL.Nat,
    'pendingAgents' : IDL.Nat,
    'approvedAgents' : IDL.Nat,
    'approvalRate' : IDL.Float64,
    'rejectedAgents' : IDL.Nat,
    'rejectionRate' : IDL.Float64,
  }),
  'recentChanges' : IDL.Vec(AgentInfo),
});
export const AttendanceAgentRecord = IDL.Record({
  'agentName' : IDL.Text,
  'checkInTime' : Time,
  'checkOutTime' : IDL.Opt(Time),
  'agentMobile' : IDL.Text,
});
export const FaceVerificationResult = IDL.Record({
  'confidenceScore' : IDL.Nat,
  'message' : IDL.Text,
  'isSuccess' : IDL.Bool,
  'faceDataHash' : IDL.Text,
});
export const LocationData = IDL.Record({
  'latitude' : IDL.Float64,
  'locationTimestamp' : IDL.Nat,
  'longitude' : IDL.Float64,
  'accuracy' : IDL.Opt(IDL.Float64),
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'faceVerification' : FaceVerificationResult,
  'agentName' : IDL.Text,
  'agentId' : IDL.Principal,
  'checkInTime' : Time,
  'checkOutTime' : IDL.Opt(Time),
  'agentMobile' : IDL.Text,
  'isValid' : IDL.Bool,
  'location' : LocationData,
});
export const PaginatedAttendanceRecords = IDL.Record({
  'total' : IDL.Nat,
  'records' : IDL.Vec(AttendanceRecord),
  'hasNextPage' : IDL.Bool,
});
export const PaginatedCustomers = IDL.Record({
  'total' : IDL.Nat,
  'hasNextPage' : IDL.Bool,
  'customers' : IDL.Vec(Customer),
});
export const PaginatedLeads = IDL.Record({
  'total' : IDL.Nat,
  'leads' : IDL.Vec(Lead),
  'hasNextPage' : IDL.Bool,
});
export const CsvAttendanceRecord = IDL.Record({
  'faceVerification' : IDL.Text,
  'agentName' : IDL.Text,
  'checkInTime' : IDL.Int,
  'attendanceDate' : IDL.Int,
  'checkOutTime' : IDL.Int,
  'agentMobile' : IDL.Text,
  'location' : IDL.Text,
});
export const CsvReport = IDL.Record({
  'agentName' : IDL.Text,
  'attendanceRecords' : IDL.Vec(CsvAttendanceRecord),
  'agentMobile' : IDL.Text,
});
export const CustomerProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const CustomerQueryResponse = IDL.Record({
  'id' : IDL.Nat,
  'queryType' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'contactNumber' : IDL.Opt(IDL.Text),
});
export const OverviewMetrics = IDL.Record({
  'recentCustomers' : IDL.Vec(Customer),
  'customerQueryStats' : IDL.Record({
    'openQueries' : IDL.Nat,
    'totalQueries' : IDL.Nat,
    'inProgressQueries' : IDL.Nat,
    'closedQueries' : IDL.Nat,
    'resolvedQueries' : IDL.Nat,
  }),
  'rentQueries' : IDL.Record({
    'resolved' : IDL.Nat,
    'closed' : IDL.Nat,
    'total' : IDL.Nat,
    'open' : IDL.Nat,
    'inProgress' : IDL.Nat,
  }),
  'validCheckIns' : IDL.Nat,
  'totalLeads' : IDL.Nat,
  'todayCheckIns' : IDL.Nat,
  'conversionRate' : IDL.Float64,
  'recentLeads' : IDL.Vec(Lead),
  'salesQueries' : IDL.Record({
    'resolved' : IDL.Nat,
    'closed' : IDL.Nat,
    'total' : IDL.Nat,
    'open' : IDL.Nat,
    'inProgress' : IDL.Nat,
  }),
  'totalCustomers' : IDL.Nat,
  'interiorQueries' : IDL.Record({
    'resolved' : IDL.Nat,
    'closed' : IDL.Nat,
    'total' : IDL.Nat,
    'open' : IDL.Nat,
    'inProgress' : IDL.Nat,
  }),
  'currentDayCheckIns' : IDL.Nat,
  'agentApprovalMetrics' : IDL.Record({
    'agentCountPerStatus' : IDL.Record({
      'pending' : IDL.Nat,
      'approved' : IDL.Nat,
      'rejected' : IDL.Nat,
    }),
    'totalAgents' : IDL.Nat,
    'pendingAgents' : IDL.Nat,
    'approvedAgents' : IDL.Nat,
    'rejectedAgents' : IDL.Nat,
    'recentAgentApprovals' : IDL.Vec(AgentInfo),
  }),
  'pendingFollowUps' : IDL.Nat,
  'recentFollowUps' : IDL.Vec(FollowUp),
});
export const WhatsAppConfig = IDL.Record({
  'isActive' : IDL.Bool,
  'apiKey' : IDL.Text,
  'businessNumber' : IDL.Text,
});
export const WhatsAppMessageLog = IDL.Record({
  'id' : IDL.Nat,
  'messageContent' : IDL.Text,
  'sentStatus' : IDL.Bool,
  'leadId' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([Customer], [IDL.Nat], []),
  'addCustomerQuery' : IDL.Func([CustomerQuery], [IDL.Nat], []),
  'addFollowUp' : IDL.Func([FollowUp], [IDL.Nat], []),
  'addLead' : IDL.Func([Lead], [IDL.Nat], []),
  'addTemplate' : IDL.Func([MessageTemplate], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignLead' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'changeAgentApprovalStatus' : IDL.Func(
      [IDL.Principal, ApprovalStatus],
      [],
      [],
    ),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'deleteTemplate' : IDL.Func([IDL.Nat], [], []),
  'getAgentCustomerQueries' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CustomerQuery)],
      ['query'],
    ),
  'getAgentPanelData' : IDL.Func([], [AgentPanelData], ['query']),
  'getAllAttendanceAgentRecords' : IDL.Func(
      [],
      [IDL.Vec(AttendanceAgentRecord)],
      ['query'],
    ),
  'getAllAttendanceRecords' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedAttendanceRecords],
      ['query'],
    ),
  'getAllCustomerQueries' : IDL.Func([], [IDL.Vec(CustomerQuery)], ['query']),
  'getAllCustomers' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedCustomers],
      ['query'],
    ),
  'getAllFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
  'getAllLeads' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginatedLeads],
      ['query'],
    ),
  'getAllTemplates' : IDL.Func([], [IDL.Vec(MessageTemplate)], ['query']),
  'getAttendanceAgentRecords' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AttendanceAgentRecord)],
      ['query'],
    ),
  'getAttendanceRecords' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceRecordsCsvReport' : IDL.Func(
      [IDL.Principal],
      [CsvReport],
      ['query'],
    ),
  'getCRMDashboardData' : IDL.Func(
      [],
      [
        IDL.Record({
          'templates' : IDL.Vec(MessageTemplate),
          'customerProfiles' : IDL.Vec(CustomerProfile),
          'messages' : IDL.Vec(Message),
          'leads' : IDL.Vec(Lead),
          'customerQueryResponses' : IDL.Vec(CustomerQueryResponse),
          'customerQueries' : IDL.Vec(CustomerQuery),
          'followUps' : IDL.Vec(FollowUp),
          'customers' : IDL.Vec(Customer),
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getCustomerDashboardData' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'queries' : IDL.Vec(CustomerQueryResponse),
          'confirmationMessage' : IDL.Text,
          'profiles' : IDL.Vec(CustomerProfile),
        }),
      ],
      ['query'],
    ),
  'getCustomerPanels' : IDL.Func(
      [],
      [
        IDL.Record({
          'rentPanel' : IDL.Vec(CustomerQuery),
          'salesPanel' : IDL.Vec(CustomerQuery),
          'interiorPanel' : IDL.Vec(CustomerQuery),
        }),
      ],
      ['query'],
    ),
  'getCustomerProfile' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'getCustomerProfileByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'getCustomerQueriesByPhoneNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CustomerQueryResponse)],
      ['query'],
    ),
  'getCustomerQuery' : IDL.Func([IDL.Nat], [IDL.Opt(CustomerQuery)], ['query']),
  'getFollowUp' : IDL.Func([IDL.Nat], [IDL.Opt(FollowUp)], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getOverviewMetrics' : IDL.Func([], [OverviewMetrics], ['query']),
  'getQueryConfirmationMessage' : IDL.Func([], [IDL.Text], ['query']),
  'getTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(MessageTemplate)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWhatsAppConfig' : IDL.Func([], [IDL.Opt(WhatsAppConfig)], ['query']),
  'getWhatsAppMessageLogs' : IDL.Func(
      [],
      [IDL.Vec(WhatsAppMessageLog)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'logWhatsAppMessage' : IDL.Func([WhatsAppMessageLog], [IDL.Nat], []),
  'recordAttendance' : IDL.Func([AttendanceRecord], [IDL.Nat], []),
  'registerCustomerProfile' : IDL.Func([CustomerProfile], [IDL.Nat], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setWhatsAppConfig' : IDL.Func([WhatsAppConfig], [], []),
  'submitCustomerQueryResponse' : IDL.Func(
      [CustomerQueryResponse],
      [IDL.Nat],
      [],
    ),
  'updateCustomer' : IDL.Func([IDL.Nat, Customer], [], []),
  'updateCustomerQuery' : IDL.Func([IDL.Nat, CustomerQuery], [], []),
  'updateFollowUp' : IDL.Func([IDL.Nat, FollowUp], [], []),
  'updateLead' : IDL.Func([IDL.Nat, Lead], [], []),
  'updateTemplate' : IDL.Func([IDL.Nat, MessageTemplate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ServiceRecord = IDL.Record({
    'cost' : IDL.Opt(IDL.Nat),
    'date' : Time,
    'description' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'serviceHistory' : IDL.Vec(ServiceRecord),
  });
  const QueryStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const CustomerQuery = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : QueryStatus,
    'flatType' : IDL.Text,
    'rentRange' : IDL.Nat,
    'assignedAgent' : IDL.Opt(IDL.Principal),
    'createdAt' : Time,
    'contactPhone' : IDL.Text,
  });
  const FollowUp = IDL.Record({
    'id' : IDL.Nat,
    'completed' : IDL.Bool,
    'dueDate' : Time,
    'notes' : IDL.Opt(IDL.Text),
    'customerId' : IDL.Nat,
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'lost' : IDL.Null,
    'contacted' : IDL.Null,
    'converted' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeadStatus,
    'assignedAgent' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const TemplateCategory = IDL.Variant({
    'support' : IDL.Null,
    'sales' : IDL.Null,
    'followUp' : IDL.Null,
    'general' : IDL.Null,
  });
  const MessageTemplate = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Time,
    'category' : TemplateCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AgentInfo = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'approvalStatus' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const AgentPanelData = IDL.Record({
    'agents' : IDL.Vec(AgentInfo),
    'agentStats' : IDL.Record({
      'totalAgents' : IDL.Nat,
      'pendingAgents' : IDL.Nat,
      'approvedAgents' : IDL.Nat,
      'approvalRate' : IDL.Float64,
      'rejectedAgents' : IDL.Nat,
      'rejectionRate' : IDL.Float64,
    }),
    'recentChanges' : IDL.Vec(AgentInfo),
  });
  const AttendanceAgentRecord = IDL.Record({
    'agentName' : IDL.Text,
    'checkInTime' : Time,
    'checkOutTime' : IDL.Opt(Time),
    'agentMobile' : IDL.Text,
  });
  const FaceVerificationResult = IDL.Record({
    'confidenceScore' : IDL.Nat,
    'message' : IDL.Text,
    'isSuccess' : IDL.Bool,
    'faceDataHash' : IDL.Text,
  });
  const LocationData = IDL.Record({
    'latitude' : IDL.Float64,
    'locationTimestamp' : IDL.Nat,
    'longitude' : IDL.Float64,
    'accuracy' : IDL.Opt(IDL.Float64),
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'faceVerification' : FaceVerificationResult,
    'agentName' : IDL.Text,
    'agentId' : IDL.Principal,
    'checkInTime' : Time,
    'checkOutTime' : IDL.Opt(Time),
    'agentMobile' : IDL.Text,
    'isValid' : IDL.Bool,
    'location' : LocationData,
  });
  const PaginatedAttendanceRecords = IDL.Record({
    'total' : IDL.Nat,
    'records' : IDL.Vec(AttendanceRecord),
    'hasNextPage' : IDL.Bool,
  });
  const PaginatedCustomers = IDL.Record({
    'total' : IDL.Nat,
    'hasNextPage' : IDL.Bool,
    'customers' : IDL.Vec(Customer),
  });
  const PaginatedLeads = IDL.Record({
    'total' : IDL.Nat,
    'leads' : IDL.Vec(Lead),
    'hasNextPage' : IDL.Bool,
  });
  const CsvAttendanceRecord = IDL.Record({
    'faceVerification' : IDL.Text,
    'agentName' : IDL.Text,
    'checkInTime' : IDL.Int,
    'attendanceDate' : IDL.Int,
    'checkOutTime' : IDL.Int,
    'agentMobile' : IDL.Text,
    'location' : IDL.Text,
  });
  const CsvReport = IDL.Record({
    'agentName' : IDL.Text,
    'attendanceRecords' : IDL.Vec(CsvAttendanceRecord),
    'agentMobile' : IDL.Text,
  });
  const CustomerProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const CustomerQueryResponse = IDL.Record({
    'id' : IDL.Nat,
    'queryType' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'contactNumber' : IDL.Opt(IDL.Text),
  });
  const OverviewMetrics = IDL.Record({
    'recentCustomers' : IDL.Vec(Customer),
    'customerQueryStats' : IDL.Record({
      'openQueries' : IDL.Nat,
      'totalQueries' : IDL.Nat,
      'inProgressQueries' : IDL.Nat,
      'closedQueries' : IDL.Nat,
      'resolvedQueries' : IDL.Nat,
    }),
    'rentQueries' : IDL.Record({
      'resolved' : IDL.Nat,
      'closed' : IDL.Nat,
      'total' : IDL.Nat,
      'open' : IDL.Nat,
      'inProgress' : IDL.Nat,
    }),
    'validCheckIns' : IDL.Nat,
    'totalLeads' : IDL.Nat,
    'todayCheckIns' : IDL.Nat,
    'conversionRate' : IDL.Float64,
    'recentLeads' : IDL.Vec(Lead),
    'salesQueries' : IDL.Record({
      'resolved' : IDL.Nat,
      'closed' : IDL.Nat,
      'total' : IDL.Nat,
      'open' : IDL.Nat,
      'inProgress' : IDL.Nat,
    }),
    'totalCustomers' : IDL.Nat,
    'interiorQueries' : IDL.Record({
      'resolved' : IDL.Nat,
      'closed' : IDL.Nat,
      'total' : IDL.Nat,
      'open' : IDL.Nat,
      'inProgress' : IDL.Nat,
    }),
    'currentDayCheckIns' : IDL.Nat,
    'agentApprovalMetrics' : IDL.Record({
      'agentCountPerStatus' : IDL.Record({
        'pending' : IDL.Nat,
        'approved' : IDL.Nat,
        'rejected' : IDL.Nat,
      }),
      'totalAgents' : IDL.Nat,
      'pendingAgents' : IDL.Nat,
      'approvedAgents' : IDL.Nat,
      'rejectedAgents' : IDL.Nat,
      'recentAgentApprovals' : IDL.Vec(AgentInfo),
    }),
    'pendingFollowUps' : IDL.Nat,
    'recentFollowUps' : IDL.Vec(FollowUp),
  });
  const WhatsAppConfig = IDL.Record({
    'isActive' : IDL.Bool,
    'apiKey' : IDL.Text,
    'businessNumber' : IDL.Text,
  });
  const WhatsAppMessageLog = IDL.Record({
    'id' : IDL.Nat,
    'messageContent' : IDL.Text,
    'sentStatus' : IDL.Bool,
    'leadId' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([Customer], [IDL.Nat], []),
    'addCustomerQuery' : IDL.Func([CustomerQuery], [IDL.Nat], []),
    'addFollowUp' : IDL.Func([FollowUp], [IDL.Nat], []),
    'addLead' : IDL.Func([Lead], [IDL.Nat], []),
    'addTemplate' : IDL.Func([MessageTemplate], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignLead' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'changeAgentApprovalStatus' : IDL.Func(
        [IDL.Principal, ApprovalStatus],
        [],
        [],
      ),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'deleteTemplate' : IDL.Func([IDL.Nat], [], []),
    'getAgentCustomerQueries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CustomerQuery)],
        ['query'],
      ),
    'getAgentPanelData' : IDL.Func([], [AgentPanelData], ['query']),
    'getAllAttendanceAgentRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceAgentRecord)],
        ['query'],
      ),
    'getAllAttendanceRecords' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedAttendanceRecords],
        ['query'],
      ),
    'getAllCustomerQueries' : IDL.Func([], [IDL.Vec(CustomerQuery)], ['query']),
    'getAllCustomers' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedCustomers],
        ['query'],
      ),
    'getAllFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
    'getAllLeads' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginatedLeads],
        ['query'],
      ),
    'getAllTemplates' : IDL.Func([], [IDL.Vec(MessageTemplate)], ['query']),
    'getAttendanceAgentRecords' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AttendanceAgentRecord)],
        ['query'],
      ),
    'getAttendanceRecords' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceRecordsCsvReport' : IDL.Func(
        [IDL.Principal],
        [CsvReport],
        ['query'],
      ),
    'getCRMDashboardData' : IDL.Func(
        [],
        [
          IDL.Record({
            'templates' : IDL.Vec(MessageTemplate),
            'customerProfiles' : IDL.Vec(CustomerProfile),
            'messages' : IDL.Vec(Message),
            'leads' : IDL.Vec(Lead),
            'customerQueryResponses' : IDL.Vec(CustomerQueryResponse),
            'customerQueries' : IDL.Vec(CustomerQuery),
            'followUps' : IDL.Vec(FollowUp),
            'customers' : IDL.Vec(Customer),
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getCustomerDashboardData' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'queries' : IDL.Vec(CustomerQueryResponse),
            'confirmationMessage' : IDL.Text,
            'profiles' : IDL.Vec(CustomerProfile),
          }),
        ],
        ['query'],
      ),
    'getCustomerPanels' : IDL.Func(
        [],
        [
          IDL.Record({
            'rentPanel' : IDL.Vec(CustomerQuery),
            'salesPanel' : IDL.Vec(CustomerQuery),
            'interiorPanel' : IDL.Vec(CustomerQuery),
          }),
        ],
        ['query'],
      ),
    'getCustomerProfile' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getCustomerProfileByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getCustomerQueriesByPhoneNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CustomerQueryResponse)],
        ['query'],
      ),
    'getCustomerQuery' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CustomerQuery)],
        ['query'],
      ),
    'getFollowUp' : IDL.Func([IDL.Nat], [IDL.Opt(FollowUp)], ['query']),
    'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getOverviewMetrics' : IDL.Func([], [OverviewMetrics], ['query']),
    'getQueryConfirmationMessage' : IDL.Func([], [IDL.Text], ['query']),
    'getTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(MessageTemplate)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWhatsAppConfig' : IDL.Func([], [IDL.Opt(WhatsAppConfig)], ['query']),
    'getWhatsAppMessageLogs' : IDL.Func(
        [],
        [IDL.Vec(WhatsAppMessageLog)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'logWhatsAppMessage' : IDL.Func([WhatsAppMessageLog], [IDL.Nat], []),
    'recordAttendance' : IDL.Func([AttendanceRecord], [IDL.Nat], []),
    'registerCustomerProfile' : IDL.Func([CustomerProfile], [IDL.Nat], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setWhatsAppConfig' : IDL.Func([WhatsAppConfig], [], []),
    'submitCustomerQueryResponse' : IDL.Func(
        [CustomerQueryResponse],
        [IDL.Nat],
        [],
      ),
    'updateCustomer' : IDL.Func([IDL.Nat, Customer], [], []),
    'updateCustomerQuery' : IDL.Func([IDL.Nat, CustomerQuery], [], []),
    'updateFollowUp' : IDL.Func([IDL.Nat, FollowUp], [], []),
    'updateLead' : IDL.Func([IDL.Nat, Lead], [], []),
    'updateTemplate' : IDL.Func([IDL.Nat, MessageTemplate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };